replicaCount: 3

image:
  tag: jvm
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

domainPrefix: rbn/prod
apiKey: prod-secret-key

config:
  envInfo: prod

security:
  networkPolicy: true
  rbacIam: true