apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-nginx-to-ingressgateway
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      ports:
        - port: 8080   # pod port (Service port 80 maps to pod port 8080)
          protocol: TCP