spring:
  application:
    name: products

service:
  envInfo: ${ENV_INFO}
  productsUrl: ${PRODUCTS_URL}
  x-api-key: ${PRODUCTS_API_KEY}

server.port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.user: ${LOG_LEVEL_APP:DEBUG}