apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-health-check
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: {{ .Values.readinessProbe.path }}
        port: {{ .Values.config.serverPort }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}