apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # Workload Identity binding: tells GKE this KSA is allowed to impersonate the GCP SA.
    # The GCP SA must also have roles/iam.workloadIdentityUser granted to this KSA (done via Terraform in iac/).
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccount }}@{{ .Values.gcp.project }}.iam.gserviceaccount.com