apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-users-to-products
spec:
  selector:
    matchLabels:
      app: products # targets the products pods only
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/dev/sa/users" # users SA in dev namespace
              - "cluster.local/ns/prod/sa/users" # users SA in prod namespace
    - to:
        - operation:
            paths: ["/actuator/health/readiness"] # allows GCP load balancer health checks (no identity)
