apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-users-to-products
spec:
  selector:
    matchLabels:
      app: products
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/dev/sa/users"
              - "cluster.local/ns/prod/sa/users"
