apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-deny-no-api-key
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  action: DENY
  rules:
    - when:
        - key: request.headers[x-api-key]
          notValues: ["{{ .Values.apiKey }}"]
