apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - match:
        - uri:
            prefix: /products
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
