.PHONY: init plan apply destroy fmt validate

init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply

apply-auto:
	terraform apply -auto-approve

destroy:
	terraform destroy

destroy-auto:
	terraform destroy -auto-approve

fmt:
	terraform fmt

validate:
	terraform validate
