replicaCount: 1

image:
  tag: jvm
  pullPolicy: Never

service:
  type: ClusterIP

domainPrefix: rbn/dev
apiKey: dev-secret-key

config:
  envInfo: dev
  serverPort: 8080
  productsUrl: http://products-dev:8080
  productsApiKey: dev-secret-key

