replicaCount: 3

image:
  tag: jvm
  pullPolicy: Never

service:
  type: ClusterIP

domainPrefix: rbn/prod
apiKey: prod-secret-key

config:
  envInfo: prod
  serverPort: 8080
  productsUrl: http://products-prod:8080
  productsApiKey: prod-secret-key

